---
engines:
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - ruby
    exclude_paths:
      - lib/elftools/structs.rb
  fixme:
    enabled: false
  rubocop:
    enabled: false
ratings:
  paths:
  - Gemfile.lock
  - "**.rb"
exclude_paths:
- spec/
- examples/
